### ISSUE TITLE
Support for AccelerationStructure

### ISSUE THREAD

**Issue by turanszkij** [KhronosGroup/SPIRV-Reflect#100]
Hello, 

Can we expect to get the AccelerationStructure types being reflected in the future? I want to migrate from SPIRV-Cross library's reflection as this library is smaller and I only need reflection. Is this library going to be maintained in the future, or is it preferred to use Spirv-Cross?

**Comment by chaoticbob** [comment]
Ray tracing and mesh shader support is being slowly added in. Sorry it's going a bit slower than we'd all like.

**Comment by turanszkij** [comment]
Thank you for getting back to me. That's good news!

**Comment by wolfgangfengel** [comment]
Let us know if you need more feedback or help in testing. We are very interested in making it part of The Forge.

@chaoticbob thanks for all the support and help!

**Comment by chaoticbob** [comment]
Support for AccelerationStructure and ray query has been added. Commit https://github.com/KhronosGroup/SPIRV-Reflect/commit/d9076429c6607e4cc3873818cfe8521568ebd01e has everything including test cases. 

I only had HLSL test cases available.

If you run into anything please include a SPV to this issue and I'll take a look.

**Comment by turanszkij** [comment]
Excellent news, thanks!

**Comment by chaoticbob** [comment]
Please reopen this issue if you encounter any problems.
