### ISSUE TITLE
Boolean Specialization Constants

### ISSUE THREAD

**Issue by reduz** [KhronosGroup/SPIRV-Reflect#121]
I am checking SPIRV-Reflect, but I see nowhere where the list of boolean specialization constants can be obtained from a stage. Is this supported?

**Comment by reduz** [comment]
Ended up implementing this in our local fork, for anyone interested:
https://github.com/godotengine/godot/pull/50325

If there is any interest in me submitting a PR with my changes, please let me know.

**Comment by chaoticbob** [comment]
Hi,

Specialization constants haven't gotten a lot of love since unfortunately. It's on my list of thing sto investigate but haven't gotten to it yet. It would be greatly appreciated if you could submit a PR. It would at least get teh ball rolling on specialization constants.

Thanks,
Hai

**Comment by reduz** [comment]
Alright, a PR will be submitted soon!

**Comment by chaoticbob** [comment]
Thanks! Looking forward to it.

**Comment by pushrax** [comment]
I'm about to implement this in another engine, @reduz any chance of a PR any time soon?
