### ISSUE TITLE
Structures with generic names in global namespace can cause conflicts in client applications

### ISSUE THREAD

**Issue by pouleyKetchoupp** [KhronosGroup/SPIRV-Reflect#122]
Internal structures like `String`, `Node`, `Parser`, `Function` are in global namespace and can lead to issues in client applications due to conflicting names in the global namespace.

As an example, we're having a MSVC debugger issue with `String` in Godot Engine, see the discussion here:
https://github.com/godotengine/godot/pull/50025

What about giving these structures more specific names, like using `Spv` or `Spirv` prefix to prevent this kind of issue in applications using the library?

**Comment by chaoticbob** [comment]
Sorry that this is causing these application giref, what you're suggesting is totally reasonable. Very much and oversight, I will make some time soon to fix it per your suggestion.

**Comment by pouleyKetchoupp** [comment]
Amazing, thank you!

**Comment by chaoticbob** [comment]
Added `SpvReflectPrv` for SPIRV-Refelct Private types that are only used in `spirv-reflect.c`. This *should* solve the problem that Godot Engine is running into...as well as prevent any future collisions. `SprvReflectPrv` should also prevent any confusion with public facing types that use the `SpvReflect` prefix.
