### ISSUE TITLE
ERROR_SPIRV_INVALID_ID_REFERENCE when using mediump in functions

### ISSUE THREAD

**Issue by darksylinc** [KhronosGroup/SPIRV-Reflect#134]
Using `mediump` inside functions fails reflection with `SPV_REFLECT_RESULT_ERROR_SPIRV_INVALID_ID_REFERENCE`

Something as simple as:

```glsl
float saturate( float x )
{
	return clamp( x, 0, 1 );
}

void main()
{
	gl_Position = worldViewProj * vec4( vertex, 1.0 );
	outVs.uv0.xy = uv0.xy;
	outVs.uv0.x = saturate( uv0.x );
}
```

Will fail if the function is modified to either:

```glsl
float saturate( mediump float x ) // fails
{
	return clamp( x, 0, 1 );
}

mediump float saturate( float x ) // fails
{
	return clamp( x, 0, 1 );
}
```

I'm attaching two shaders. One without mediump and its generated SPIRV (using glslang) which works.
The other one with mediump and its generated SPIRV (using glslang) which fails.

This may be a glslang bug, but I suspect it's SPIRV-Reflect's. spir-val says nothing and the shader is compilable by the driver.

To be more specific it fails [here](https://github.com/KhronosGroup/SPIRV-Reflect/blob/4689b3360cb38283b67926a065a0f2cc285928b5/spirv_reflect.c#L1372).

[Shaders.zip](https://github.com/KhronosGroup/SPIRV-Reflect/files/7907809/Shaders.zip)

## Update

It seems to be an interesting oddity that `target_id` appears to be always 10, regardless of the shader. It may be a coincidence... or not.

## Update 2 FIX

OK I found out why it's crashing. With the addition of decoration parsing, it's pointing to `SpvOpFunctionParameter` and `SpvOpExtInst` which aren't normally parsed. Solution would be to either silently ignore the returned nullptr if it's just RelaxedPrecision decoration or to actually load these Ops:

```diff
diff --git a/spirv_reflect.c b/spirv_reflect.c
index 11163a9..a4b94c6 100644
--- a/spirv_reflect.c
+++ b/spirv_reflect.c
@@ -734,6 +734,16 @@ static SpvReflectResult ParseNodes(SpvReflectPrvParser* p_parser)
       }
       break;
 
+      // Needed for 'OpDecorate xx RelaxedPrecision' to work
+      // See https://github.com/KhronosGroup/SPIRV-Reflect/issues/134
+      case SpvOpFunctionParameter:
+      case SpvOpExtInst:
+      {
+        CHECKED_READU32(p_parser, p_node->word_offset + 1, p_node->result_type_id);
+        CHECKED_READU32(p_parser, p_node->word_offset + 2, p_node->result_id);
+      }
+      break;
+
       case SpvOpTypeStruct:
       {
         p_node->member_count = p_node->word_count - 2;
@@ -4935,4 +4945,4 @@ const char* spvReflectBlockVariableTypeName(
         return NULL;
     }
     return p_var->type_description->type_name;
-}
\ No newline at end of file
+}
```

## Update 3

It happened again this time with an `OpFMul`. I don't think it's reasonable to load all those Ops. I'll just go with plan B and ignore the return value on RelaxedPrecision decorations.

This solution works for me:

```diff
diff --git a/spirv_reflect.c b/spirv_reflect.c
index 11163a9..bef1ade 100644
--- a/spirv_reflect.c
+++ b/spirv_reflect.c
@@ -1368,7 +1368,11 @@ static SpvReflectResult ParseDecorations(SpvReflectPrvParser* p_parser)
     uint32_t target_id = 0;
     CHECKED_READU32(p_parser, p_node->word_offset + 1, target_id);
     SpvReflectPrvNode* p_target_node = FindNode(p_parser, target_id);
     if (IsNull(p_target_node)) {
+      if (p_node->op == (uint32_t)SpvOpDecorate && decoration == SpvDecorationRelaxedPrecision) {
+        // Many OPs can be decorated that we don't care about. Ignore those
+        // See https://github.com/KhronosGroup/SPIRV-Reflect/issues/134
+        continue;
+      }
       return SPV_REFLECT_RESULT_ERROR_SPIRV_INVALID_ID_REFERENCE;
     }
     // Get decorations
```

**Comment by chaoticbob** [comment]
Hi - thanks for the fix. I manually merged it in. Let me know if this comes up again.
