### ISSUE TITLE
Compilation Broken On All Platforms When Building As C++ Due To Invalid Cast from void* to uint32_t*

### ISSUE THREAD

**Issue by benn-geomagical** [KhronosGroup/SPIRV-Reflect#143]
Introduced into spirv_reflect.c by commit fb708aa059a06fff0dcbeeb4831cfa2e9247f609 on 2022-01-30

in static SpvReflectResult CreateShaderModule()
line 3560:
`p_module->_internal->spirv_code = (void*)p_code; // cast that const away`

**Comment by chaoticbob** [comment]
Hi - sorry about this. It slipped my mind that we didn't have a compile as C++ already. I've made the fix and added a test for it. Let me know if you run into anything else.

**Comment by benn-geomagical** [comment]
Thank you so much!
