### ISSUE TITLE
Reading data from stdin

### ISSUE THREAD

**Issue by dpwiz** [KhronosGroup/SPIRV-Reflect#148]
I'd be glad for a way to run `spirv-reflect` without creating input files.

```bash
gen-spv | spirv-reflect -v 1 -y - | load-yaml
```
or
```python
yaml = subprocess.run(["spirv-reflect", "-v", "1", "-y", "-"], stdin=PIPE, input=spirv).stdout
```

**Comment by chaoticbob** [comment]
Thanks for the FR. Let me see how I can make this happen.

**Comment by Dunedan** [comment]
I'd be interested in being able to provide the input for `spirv-reflect` via stdin as well to avoid unnecessary disk IO.

**Comment by spencer-lunarg** [comment]
thanks for pining thing @Dunedan , was able to get a quick patch up
