### ISSUE TITLE
calloc size for strings

### ISSUE THREAD

**Issue by acaly** [KhronosGroup/SPIRV-Reflect#156]
Currently, raw strings are allocated by `calloc` with element count of string length but element size of `sizeof(char*)`. This will allocate 4 times as more memory on 32-bit platforms or 8 times on 64-bit platforms.

For example: https://github.com/KhronosGroup/SPIRV-Reflect/blob/b68b5a8a5d8ab5fce79e6596f3a731291046393a/spirv_reflect.c#L692-L704

**Comment by Ace17** [comment]
https://github.com/KhronosGroup/SPIRV-Reflect/pull/159

**Comment by chaoticbob** [comment]
Apologies for the bug. I've merged PR #159. Thanks @Ace17 for the fix!
