### ISSUE TITLE
Support for CooperativeMatrix extension?

### ISSUE THREAD

**Issue by ib00** [KhronosGroup/SPIRV-Reflect#160]
I know this is Nvidia only extension at the moment, but is there a
plan to support cooperative matrix extensions (GL_NV_cooperative_matrix, GL_NV_integer_cooperative_matrix)?

Examples are here:
https://github.com/jeffbolznv/vk_cooperative_matrix_perf/tree/master/shaders

More and more shaders are using this extension.

**Comment by ProgrammierPatrick** [comment]
Hi, I  also started using GL_NV_cooperative_matrix recently in a project. When using the extension, spirv-reflect kept crashing.

My fix was to add this case to `ParseNodes(SpvReflectPrvParser*)` in `spirv_reflect.c`:

```
--- a/extern/SPIRV-Reflect/spirv_reflect.c
+++ b/extern/SPIRV-Reflect/spirv_reflect.c
@@ -762,6 +762,7 @@ static SpvReflectResult ParseNodes(SpvReflectPrvParser* p_parser)
       case SpvOpTypePipe:
       case SpvOpTypeAccelerationStructureKHR:
       case SpvOpTypeRayQueryKHR:
+      case SpvOpTypeCooperativeMatrixNV:
       {
         CHECKED_READU32(p_parser, p_node->word_offset + 1, p_node->result_id);
         p_node->is_type = true;
```

In my understanding of spirv-reflect this just interprets the fcoopmatNV as an opaque type without any introspection, but allows the parser to not fail in parsing the file.

I do not know enough about spirv-reflect to know if this is a good idea. Maybe a developer can look into this and decide if this fix can be merged?
