### ISSUE TITLE
Update the README.md file for extra dependency

### ISSUE THREAD

**Issue by alexpanter** [KhronosGroup/SPIRV-Reflect#173]
Hi,
The README file say this:

> Integration

> SPIRV-Reflect is designed to make integration as easy as possible. The only external dependency is the [Vulkan SDK](https://vulkan.lunarg.com/sdk/home).

> To integrate SPIRV-Reflect into a project, simply add spirv_reflect.h and spirv_reflect.c in the project's build, and include spirv_reflect.h from the necessary source files.

But it would seem that copying the file `include/spirv/unified1/spirv.h` is also necessary. So I would propose updating the text accordingly.

**Comment by chaoticbob** [comment]
Hi - this has been an annoying philsophical bug for a while. SPIRV-Reflect doesn't necessarily have to use `include/spirv/unified1/spirv.h`. It can be used with whatever `spirv.h` is inside a user's include path assuming it's up to date. But to your point, the documentation could be more clear about this. Will update.
