### ISSUE TITLE
Getting error 20 code (SPV_REFLECT_RESULT_ERROR_SPIRV_INVALID_EXECUTION_MODE) when trying to use functions from extension GL_ARB_fragment_shader_interlock

### ISSUE THREAD

**Issue by TheDonsky** [KhronosGroup/SPIRV-Reflect#185]
Hello,

Added GL_ARB_fragment_shader_interlock extension to code with a regular beginInvocationInterlockARB() - endInvocationInterlockARB()usage.

Code is compiled all right, but spvReflectCreateShaderModule gives me error code 20.

If I remove references to beginInvocationInterlockARB, endInvocationInterlockARB and sample_interlock_ordered, error goes away, but obviously, that's not a solution.

Any idea what can be done about this?

**Comment by TheDonsky** [comment]
Adding a "special case" for 5336 inside spirv_reflect.c ParseExecutionModes line 3279 removed the error for me:
![image](https://github.com/KhronosGroup/SPIRV-Reflect/assets/19620595/63df1f71-495a-4f36-97e8-04a985f736d4)

I guess, the clean solution would be to add an enumeration value to SpvExecutionMode_ and add case at the end of that switch-case statement; I can make a pull request, but I am not familiar enough with the project internals to be sure that it will not break anything

**Comment by TheDonsky** [comment]
Small update: 
I found interlocking enumeration values already in spirv.h; All that's actually needed is inserting those in switch-case statement

**Comment by TheDonsky** [comment]
Added a pull request: https://github.com/KhronosGroup/SPIRV-Reflect/pull/186

**Comment by spencer-lunarg** [comment]
@TheDonsky  did https://github.com/KhronosGroup/SPIRV-Reflect/pull/186 solve this? Can we close this issue then?

**Comment by TheDonsky** [comment]
Yes, it seems to be resolved on my side
