### ISSUE TITLE
Remove support for bazel builds

### ISSUE THREAD

**Issue by dnovillo** [KhronosGroup/SPIRV-Reflect#188]
We used to need bazel support at Google, but that is no longer the case.  @chaoticbob any concerns with removing it?  Are there any downstream users who rely on it?

**Comment by chaoticbob** [comment]
No concerns on my end. I can't be for sure if downstream users but I suspect bazel users aren't numerous. I think it's safe to remove. We'll take feedback if it turns out to be problematic for someone.

**Comment by dnovillo** [comment]
SG.  PR coming up.
