### ISSUE TITLE
missing buffer names 

### ISSUE THREAD

**Issue by madgeniusjm** [KhronosGroup/SPIRV-Reflect#278]
I've recently started using the code and noticed that I cannot retrieve names for uniform buffers in glsl. The name is always a null string. I am however ale to get the names of the buffers members. 

I believe this is a bug and would like you guys to fix it asap. Just as a test I opened my compiled spirv code in notepad++ and the actual buffer name was stored in plain text. So it's retrieval seems highly possible.

**Comment by spencer-lunarg** [comment]
can you please provide a glsl code so I can reproduce

**Comment by spencer-lunarg** [comment]
closing, @madgeniusjm if you do want reopen, please submit an example, preferably something like a Compiler Explorer link (example https://godbolt.org/z/s14W5Mx6M)
