### ISSUE TITLE
Question about type_description

### ISSUE THREAD

**Issue by redorav** [KhronosGroup/SPIRV-Reflect#283]
I'm trying to filter out RWStructuredBuffers counters from reflection. I can see that the type name has something like counter.var but I cannot see other fields with which to identify them. Is there a more reliable way to do it? Many thanks

**Comment by spencer-lunarg** [comment]
Can you provide a simple HLSL/SPIR-V example of what information you are trying to find... I guess not quite sure what is not reliable about the current way

**Comment by redorav** [comment]
[Metadata.spv.txt](https://github.com/user-attachments/files/17277061/Metadata.spv.txt)
I'm attaching the spv file so you know what I mean. The original hlsl has a RWStructuredBuffer, and dxc produces two resources from it, the main buffer and the counter. The counters have a type of type_ACSBuffer_counter.

During reflection, I check for (binding.resource_type == SPV_REFLECT_RESOURCE_FLAG_UAV) and both of those resources appear in the list (the buffer and the counter), so currently I have to resort to string comparing the name to find the string counter.var that is what spirv-reflect ends up returning for the binding name.

Hopefully it's clearer now

**Comment by redorav** [comment]
@spencer-lunarg Did that help at all? Do you need any more details?

**Comment by spencer-lunarg** [comment]
Sorry, just lost track of this issue.

> The original hlsl has a RWStructuredBuffer

Can you provide be with just that snippet of HLSL you are using? A more simplified / minimal HLSL snippet (preferably via [compiler explorer link](https://godbolt.org/z/3n9aTMKnf))

-----

So looking at the SPIR-V only, I see there is a 

```swift
%type.ACSBuffer.counter = OpTypeStruct %int
%ptr = OpTypePointer Uniform %type.ACSBuffer.counter
```

from there, I see 4 variables use it like `%var = OpVariable %136 Uniform` (which are the `counter.var.ExampleRWStructur*` handles)

... I guess I still haven't fully figured what you want and if it is something SPIRV-Reflect is missing or just DXC has lost the information when generating SPIR-V so we can't detect it

**Comment by redorav** [comment]
I apologize for not being clear, here's the hlsl. https://godbolt.org/z/fvaqG4b6z

If I put that through dxc with the -Od option, this is what I get. However I can see now that in Godbolt this doesn't appear. Could it be that either Godbolt or myself have older dxc? I could try with a newer one.

```
; SPIR-V
; Version: 1.0
; Generator: Google spiregg; 0
; Bound: 24
; Schema: 0
               OpCapability Shader
               OpMemoryModel Logical GLSL450
               OpEntryPoint Fragment %metadata "metadata" %out_var_SV_Target0
               OpExecutionMode %metadata OriginUpperLeft
          %3 = OpString "C:/Users/redorav/OneDrive/corsair-engine/Source/Rendering/Shaders/Metadata.hlsl"
               OpSource HLSL 600 %3 "

RWStructuredBuffer<float4> g_colorBuffer;



float4 metadata() : SV_Target0

{	

    return float4(0.0, 0.0, 0.0, 0.0);

}

"
               OpName %type_RWStructuredBuffer_v4float "type.RWStructuredBuffer.v4float"
               OpName %g_colorBuffer "g_colorBuffer"
               OpName %type_ACSBuffer_counter "type.ACSBuffer.counter"
               OpMemberName %type_ACSBuffer_counter 0 "counter"
               OpName %counter_var_g_colorBuffer "counter.var.g_colorBuffer"
               OpName %out_var_SV_Target0 "out.var.SV_Target0"
               OpName %metadata "metadata"
               OpName %src_metadata "src.metadata"
               OpName %bb_entry "bb.entry"
               OpDecorate %out_var_SV_Target0 Location 0
               OpDecorate %g_colorBuffer DescriptorSet 0
               OpDecorate %g_colorBuffer Binding 0
               OpDecorate %counter_var_g_colorBuffer DescriptorSet 0
               OpDecorate %counter_var_g_colorBuffer Binding 1
               OpDecorate %_runtimearr_v4float ArrayStride 16
               OpMemberDecorate %type_RWStructuredBuffer_v4float 0 Offset 0
               OpDecorate %type_RWStructuredBuffer_v4float BufferBlock
               OpMemberDecorate %type_ACSBuffer_counter 0 Offset 0
               OpDecorate %type_ACSBuffer_counter BufferBlock
      %float = OpTypeFloat 32
    %float_0 = OpConstant %float 0
    %v4float = OpTypeVector %float 4
          %9 = OpConstantComposite %v4float %float_0 %float_0 %float_0 %float_0
%_runtimearr_v4float = OpTypeRuntimeArray %v4float
%type_RWStructuredBuffer_v4float = OpTypeStruct %_runtimearr_v4float
%_ptr_Uniform_type_RWStructuredBuffer_v4float = OpTypePointer Uniform %type_RWStructuredBuffer_v4float
        %int = OpTypeInt 32 1
%type_ACSBuffer_counter = OpTypeStruct %int
%_ptr_Uniform_type_ACSBuffer_counter = OpTypePointer Uniform %type_ACSBuffer_counter
%_ptr_Output_v4float = OpTypePointer Output %v4float
       %void = OpTypeVoid
         %18 = OpTypeFunction %void
         %22 = OpTypeFunction %v4float
%g_colorBuffer = OpVariable %_ptr_Uniform_type_RWStructuredBuffer_v4float Uniform
%counter_var_g_colorBuffer = OpVariable %_ptr_Uniform_type_ACSBuffer_counter Uniform
%out_var_SV_Target0 = OpVariable %_ptr_Output_v4float Output
   %metadata = OpFunction %void None %18
         %19 = OpLabel
         %20 = OpFunctionCall %v4float %src_metadata
               OpStore %out_var_SV_Target0 %20
               OpLine %3 7 1
               OpReturn
               OpFunctionEnd
               OpLine %3 4 1
%src_metadata = OpFunction %v4float None %22
               OpNoLine
   %bb_entry = OpLabel
               OpLine %3 6 5
               OpReturnValue %9
               OpFunctionEnd
```

As you can see, the g_colorBuffer has a counter that is implicit in RWStructuredBuffers according to HLSL. I want to be able to recognize these and discard them without resorting to comparing names, if possible, because otherwise they appear as though they were regular buffers.

Hopefully that makes more sense.

**Comment by redorav** [comment]
@spencer-lunarg Sorry to have wasted your time a bit here. I have updated DXC and it no longer emits these counters in the latest versions, so I don't need to exclude them by name anymore. Thanks for your help

**Comment by spencer-lunarg** [comment]
> I have updated DXC and it no longer emits these counters in the latest versions

Ok that is good to hear, also don't worry, I am just glad things are working and nothing is broken (to my knowledge) in SPIRV-Reflect
