### ISSUE TITLE
How much does this library trust the input SPIR-V module?

### ISSUE THREAD

**Issue by dneto0** [KhronosGroup/SPIRV-Reflect#53]
The SPIR-V parser is pretty bare-bones.  How robust is it intended to be?

I'd like the README and the .h file to be update to state the assumptions about the input.

E.g.:  "The SPIR-V module is assumed to be valid for Vulkan 1.0 or 1.1"
Or is it a weaker condition?

**Comment by chaoticbob** [comment]
The parser is intended to be robust enough to parse handle resources, input and output variables, and function call chains. In the interest in maintaining speed - it won't likely get more robust than that unless it's necessary. 

SPIRV-Reflect will initially assume that a module is a valid module, but at the first sign of an error or invalid access it will bail immediately.

For instance:
- if the bound is exceeded, parsing errors out
- if a function call chain has invalid access, parsing errors out
- if a resource is referenced that doesn't exist, parsing errors out
