### ISSUE TITLE
ParseFormat does not handle doubles correctly

### ISSUE THREAD

**Issue by mtak-** [KhronosGroup/SPIRV-Reflect#68]
I think ParseFormat should be checking the width of the float/vec types in order to determine the format. https://github.com/chaoticbob/SPIRV-Reflect/blob/8394d3eedd4e62aa1bd7229426256151962539a9/spirv_reflect.c#L2118

Formats like `SPV_REFLECT_FORMAT_R64_SFLOAT`, etc. appear to be missing.

**Comment by chaoticbob** [comment]
Thanks. Do you have a small example case of something that uses a 64-bit format?

**Comment by mtak-** [comment]
FWIW, I'm generating appropriately packed data structures and bindings for vulkan that match the parsed spirv. So I do not need this for any specific shader. IIUC here's an example shader that should use a 64 bit for `in double in_thing`:

```glsl
#version 450
#extension GL_ARB_separate_shader_objects : enable

layout(std430) uniform;

uniform PassUniform { mat4 proj; };
uniform ObjectUniform { mat4 model; };

in vec2 in_position;
in vec4 in_color;
in vec2 in_tex_coord;
/////////////////////////////////////////////////////////
in double in_thing; // currently tagged as a 32 bit float
/////////////////////////////////////////////////////////

out vec4 frag_color;
out vec2 frag_tex_coord;
out double out_thing;

out gl_PerVertex {
    vec4 gl_Position;
};

void main() {
    gl_Position = proj * model * vec4(in_position, 0.0, 1.0);
    frag_color = in_color;
    frag_tex_coord = in_tex_coord;
    out_thing = in_thing;
}
```

**Comment by chaoticbob** [comment]
Thank you for the update. Apologies for the delay. Will investigate.
