### ISSUE TITLE
Issue parsing SPIRV with function taking struct parameter.

### ISSUE THREAD

**Issue by noggs** [KhronosGroup/SPIRV-Reflect#78]
I've found an unusual issue where the library returns SPV_REFLECT_RESULT_ERROR_SPIRV_INVALID_BLOCK_MEMBER_REFERENCE.
This is caused by accessing past the end of the p_access_chain->indexes[] array.

I've narrowed it down to a descriptor block which has a struct in, and a function is called which takes the struct as a parameter. The glsl for this minimal repro looks like this:
```
struct B {
	float a;
};
layout (binding = 0) uniform Test {
	B b;
} test;
float dothing(const in B b) {
	return b.a;
}
layout(location = 0) out vec4 outColor;
void main() {
	outColor = vec4(0);
	// this is fine
	outColor.z = test.b.a;
	// this line causes SPV_REFLECT_RESULT_ERROR_SPIRV_INVALID_BLOCK_MEMBER_REFERENCE
	outColor.z = dothing(test.b);
}
```

I'm using glslc.exe to compile the shader. I've attached the spirv for this version (test-broken.frag.spv) and also a version with the last line commented out (test-works.frag.spv).

I'm sorry, I was not able to understand why it is broken yet, maybe someone else could take a look too?

[test-spv.zip](https://github.com/chaoticbob/SPIRV-Reflect/files/3755972/test-spv.zip)

**Comment by noggs** [comment]
In case anyone comes to this, I have not been able to figure it out but looking through the SPIRV disasm I noticed there is an OpAccessChain with no Indexes specified. Maybe this is a codegen issue?

Anyway,  if anyone needs a dirty hack to get past this, where it goes wrong in ParseDescriptorBlockVariableUsage, you can seemingly early out of parsing the struct with no ill effects.
```
if (index_index >= p_access_chain->index_count) return SPV_REFLECT_RESULT_SUCCESS;
```

**Comment by bernief1** [comment]
I'm also running into this issue, using HLSL. It seems that if a struct inside a cbuffer is passed to a function, then spirv_reflect fails. However if a local copy of the struct is used instead, then it works. The distinction is rather subtle as well - the local copy of the struct must be copied member-by-member from the cbuffer struct, not all at once.

I have a simple repro case here. You'll need dxc.exe and dxcompiler.dll in the same directory (I got mine from https://ci.appveyor.com/project/antiagainst/directxshadercompiler/branch/master/artifacts). If you drag shader.hlsl onto shader.bat, it will generate six versions of the .spv file. The first three fail spirv_reflect, and the last 3 don't.

[cbuffer_struct_issue.zip](https://github.com/chaoticbob/SPIRV-Reflect/files/3817392/cbuffer_struct_issue.zip)

```
struct MyStruct
{
	float4 v;
};

cbuffer cb_foo
{
	MyStruct foo;
};

cbuffer cb_foo_v
{
	float4 foo_v;
};

float GetX(MyStruct s)
{
	return s.v.x;
}

float GetXFromV(float4 v)
{
	return v.x;
}

float4 Main0() : SV_TARGET0 {                                return GetX(foo);        } // <-- this crashes spirv_reflect
float4 Main1() : SV_TARGET0 { MyStruct       foo2   = foo;   return GetX(foo2);       } // <-- this crashes spirv_reflect
float4 Main2() : SV_TARGET0 { MyStruct foo2; foo2   = foo;   return GetX(foo2);       } // <-- this crashes spirv_reflect
float4 Main3() : SV_TARGET0 { MyStruct foo2; foo2.v = foo.v; return GetX(foo2);       } // <-- this does NOT crash
float4 Main4() : SV_TARGET0 {                                return GetXFromV(foo.v); } // <-- this does NOT crash
float4 Main5() : SV_TARGET0 {                                return GetXFromV(foo_v); } // <-- this does NOT crash
```

**Comment by chaoticbob** [comment]
Thanks for the issue. Sorry for the delay. Will investigate.

**Comment by darksylinc** [comment]
I'm looking into this bug because I managed to get a very interesting repro:

1. MSVC 2019 x64 and Android trigger the bug. 
1. GCC x64 on Linux works fine

I'm still researching, but so far I found that at the same location:

`uint32_t index = p_access_chain->indexes[index_index];`

Windows:

index is 4261281277, index_index = 2

Linux: 

index is 0, index_index = 2

I'll report more when I get more info

**Comment by darksylinc** [comment]
It's getting more clear: ParseDescriptorBlockVariableUsage keeps looping:
while ((p_type->op == SpvOpTypeArray) && (index_index < p_access_chain->index_count)) {
{
 p_type = ...; //p_type->op == SpvOpTypeArray may become false now
   ...
  index_index += 1;
}

The loop may result with index_index = p_access_chain->index_count; but later on ParseDescriptorBlockVariableUsage is called; producing the out of bounds read.

**Comment by lyuma** [comment]
Ran into the same problem when I declared a local variable which referenced a struct member of a uniform buffer (Godot engine master branch):
```glsl
layout(set = 0, binding = 7, std140) uniform DirectionalLights {
	DirectionalLightData data[MAX_DIRECTIONAL_LIGHT_DATA_STRUCTS];
}
directional_lights;

...
vec4 get_light_color(uint index) {
    DirectionalLightData dld = directional_lights.data[index];
    return dld.color;
}
```
I may have also hit this when returning a struct from a function, such as `DirectionalLightData get_light(uint idx) { return ......; }` but it might be conflated with the above issue.

**Comment by chaoticbob** [comment]
Thank you everyone for the information on this issue. I dug into this issue and found that the failed parse in all cases has to do with the handling of the `OpAccessChain` indices. In @bernief1's example it seems like shader compilers can "shortcut" the type hierarchy. And from @lyuma's example a similar thing happens for arrays. I have a fix that stops the crash in both cases but incorrectly marks the USED state of the variable in arrays. I'm working on a more generic fix to address this.  The `OpAccessChain` behavior in these cases are new to me and it wasn't obvious from my previous reading of the spec.

**Comment by chaoticbob** [comment]
The crash should be fixed by https://github.com/KhronosGroup/SPIRV-Reflect/commit/64b0cc260585ef4759a2a6f9923fc60cfc6f61c4. There may be some edge cases of GLSL structs that aren't covered.

Please reopen if you encounter any crashes or unexpected SPV_REFLECT_RESULT_ERROR_SPIRV_INVALID_BLOCK_MEMBER_REFERENCE.
