### ISSUE TITLE
Support for NVidia RTX extension

### ISSUE THREAD

**Issue by jcxz** [KhronosGroup/SPIRV-Reflect#85]
Hi,

would it be possible to add support for RTX shader extensions (ray generation, miss, closest hit, intersection and any hit shader types) ?

How hard or easy would that be ?

If I had to do it on my own, do you have any pointers where to start ?

**Comment by jkunstwald** [comment]
Did you find a solution in the meantime? All i've found is SPIRV-Cross, which doesn't fit quite as well and can't patch the binary in place.

**Comment by jcxz** [comment]
You can checkout my fork here: https://github.com/jcxz/SPIRV-Reflect I have added support for NVidia RTX extension, but I have not made a pull request.

**Comment by jkunstwald** [comment]
Ah i see, i also forked it and opened a PR, but it's pending. Our changes look almost identical.

**Comment by jcxz** [comment]
Awesome. Do you have any plans to also add support for the KHR version ? (I have not looked at it yet, so I am not sure how much has changed).

**Comment by jkunstwald** [comment]
As far is i can tell, the KHR enums are all aliasing to the NV versions (in Vulkan, not sure about SPIR-V), so it might be compatible right away. I would only revisit this if we decide to switch to the new KHR extension once it is properly released and supported.

**Comment by chaoticbob** [comment]
Parsing for ray tracing has been added using the KHR extension. Wherever there isn't a KHR equivalent of the NV, the NV value is parsed instead. 

Please reopen this issue if you encounter any problems.
