### ISSUE TITLE
SPIRV-Reflect is not compliant with SPIRV 1.5

### ISSUE THREAD

**Issue by darkhorse64** [KhronosGroup/SPIRV-Reflect#95]

**Comment by darkhorse64** [comment]
For OpEntryPoint, the spec says "Before version 1.4, the interface’s storage classes are limited to the Input and Output storage classes. Starting with version 1.4, the interface’s storage classes are all storage classes used in declaring all global variables referenced by the entry point’s call tree.". In **ParseInterfaceVariables**, the code flags an error if it encounters a storage class different from **Input**/**Output**. I think it should do a _continue_.

**Comment by chaoticbob** [comment]
There is a fix in place for this. Do you have SPIR-V that can be attached to the issue so it can be tested against the fix to make sure it addresses the issue that you're encountering?

**Comment by chaoticbob** [comment]
Support for SPIRV 1.5 entry point has been added. Please reopen and include SPIRV binary if you're still running into issues.
